name: hmda_privacy_governance
version: 1.0.0
config-version: 2
profile: hmda_privacy_governance
model-paths: ["models"]
test-paths: ["dbt_tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  hmda_privacy_governance:
    staging:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
vars:
  minimum_cell_size: 20
  county_income_band_width: 25000
  county_loan_amount_band_width: 50000
  state_income_band_width: 50000
  state_loan_amount_band_width: 100000
