version: 1
configurations:
  cfpb_current_unsuppressed:
    geography: tract
    income_band_width: null
    loan_amount_band_width: null
    suppress_k_below: null
  cfpb_current:
    geography: tract
    income_band_width: null
    loan_amount_band_width: null
    suppress_k_below: 5
  county_geo:
    geography: county
    income_band_width: null
    loan_amount_band_width: null
    suppress_k_below: 5
  county_banded:
    geography: county
    income_band_width: 25000
    loan_amount_band_width: 50000
    suppress_k_below: 5
  state_banded:
    geography: state
    income_band_width: 50000
    loan_amount_band_width: 100000
    suppress_k_below: 5
